export const ELEMENTS = {
    titleSearchPage: 'h1.Heading--title',
    tabSearchAdvanced: 'li[class="react-tabs__tab"]',
    selectSpecialty: 'div[class=" css-1xamc9y-placeholder"]',
    selectState: 'div[id*="province-input"]',
    selectStateDynamic: 'div[class^="Select--required-field"]',
    selectMenuDynamic: 'div[class*="css-8plzl5-menu',
    selectStateRJ: 'div#react-select-4-option-18',
    selectCity: 'div[id*="city-input"]',
    selectCityDinamic: 'div#city-input div div div input',
    selectCityAraruama: 'div#react-select-5-option-2',
    selectCityRioJaneiro: 'div#react-select-5-option-67',
    searchButton: 'button[class^="Button"]',
    labelSpecialty: 'span[class*="ProviderSpecialties--item"]',
    labelState: 'a[class="ProviderAddressAsGrid--address-link"]',
    paginatorButton: 'div[class="d-flex justify-content-center row"] button',
    paginatorButton_2: 'div[class^="d-flex"] button',
    inputCommonSearch: 'div[id="search-query-input"] input',
    inputspecialty: 'input[id="react-select-3-input"]',
    inputCity: 'input#react-select-5-input',
    divCity: 'div.css-1xamc9y-placeholder',
    inputDistrict: 'div div input#react-select-6-input',
    divDistrict: 'div div[class=" css-1xamc9y-placeholder"]',
    inputEstablishment: 'input#react-select-7-input',
    inputNetwork: 'input#react-select-8-input',
    inputQualification: 'input#react-select-10-input',
    divQualification: 'div[class="InputColumn col-lg-6"]',
    divQualificationRes: 'div[class=" css-1xamc9y-placeholder"]',
    inputPlan: 'input#react-select-9-input',
    labelEstablishment: 'div[class^="ProviderSpecialties"] span',
    doctorLabelName: 'div[class~="Provider--name"]',
    toogleEmergency: 'span[class="Switch--wrapper"] input',
    labelCityName: 'a[class*="ProviderAddressAsGrid--address-link"]',
    moreFilters: 'span[class="DetailedSearchForm--show-more-filters"] img'
}   