export const ELEMENTS = {
    titleSearchPage: 'h1.Heading--title',
    tabSearchAdvanced: 'li[class="react-tabs__tab"]',
    selectSpecialty: 'div[class=" css-1xamc9y-placeholder"]',
    selectState: 'div[id*="province-input"]',
    selectStateDynamic: 'div[class^="Select--required-field"]',
    selectMenuDynamic: 'div[class*="css-8plzl5-menu',
    selectStateRJ: 'div#react-select-4-option-18',
    selectCity: 'div[id*="city-input"]',
    selectCityDinamic: 'div#city-input div div div input',
    selectCityAraruama: 'div#react-select-5-option-2',
    selectCityRioJaneiro: 'div#react-select-5-option-67',
    searchButton: 'button[class^="Button"]',
    labelSpecialty: 'span[class*="ProviderSpecialties--item"]',
    labelState: 'div.col-lg-6 a',
    paginatorButton: 'button[class$="LoadMoreResultsButton"]',
    paginatorButton_2: 'div[class^="d-flex"] button',
    inputCommonSearch: 'input[id="react-select-2-input"]',
    inputspecialty: 'input[id="react-select-3-input"]',
    inputCity: 'input#react-select-5-input',
    inputDistrict: 'div div input#react-select-6-input',
    inputEstablishment: 'input#react-select-7-input',
    inputNetwork: 'input#react-select-8-input',
    inputQualification: 'input#react-select-10-input',
    inputPlan: 'input#react-select-9-input',
    labelEstablishment: 'span[class*="ProviderSpecialties--item"]',
    doctorLabelName: 'div.Provider--name',
    toogleEmergency: 'span[class="Switch--wrapper"] input',
    labelCityName: 'a[class*="ProviderAddressAsGrid--address-link"]',
    moreFilters: 'span[class="DetailedSearchForm--show-more-filters"] img'
}   